name: Update WNBA Game Data Daily

on:
  schedule:
    # Runs at 5 AM UTC every day (after all games are finished)
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use a stable Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run data update script
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add wnba_data_for_app.csv
          git diff --quiet --exit-code || (git commit -m "Automated daily data update" && git push)